#
# Carsten Langgaard, carstenl@mips.com
# Copyright (C) 1999,2000 MIPS Technologies, Inc.  All rights reserved.
#
# Copyright (C) 2008 Wind River Systems, Inc.
#   written by Ralf Baechle <ralf@linux-mips.org>
#
obj-y				:= am7x-cmdline.o \
				   am7x-init.o am7x-int.o \
				   am7x-memory.o am7x-mtd.o \
				   am7x-platform.o \
				   am7x-reset.o \
				   am7x-setup.o am7x-time.o \
				   am7x-board.o \
				   am7x-dma.o \
				   am7x-mempool.o \
				   am7x-sys-msg.o \
				   am7x-standby.o \
				   am7x-pm.o \
				   am7x-process.o \
				   am7x-device.o

obj-$(CONFIG_EARLY_PRINTK)	+= am7x-console.o

#EXTRA_CFLAGS += -Werror # PRC, SEP 29, 2009
