#ifndef CUSTOMIZATION_INFO_H
#define CUSTOMIZATION_INFO_H

#define UART_MAX_STRING 20
#define LONG_STRING_LEN 128
#define CUSTOM_MODEL_NUMS 10
#define CUSTOM_DEFAULT_STORAGE 1111
#define CUSTOM_VERSION_INFO_MAX_STRING 20
#define TRUE	1
#define FALSE	0

//#define ACER_DEBUG

#ifdef ACER_DEBUG
#define acer_sysdbg_info(fmt,arg...) printf("ACER PROJECTTOR MINFO[%s-%d]:" fmt"\n",__func__,__LINE__,##arg)
#else
#define acer_sysdbg_info(fmt, arg...)
#endif

#define acer_sysdbg_err(fmt,arg...) printf("ACER PROJECTTOR MERR[%s-%d]:" fmt"\n",__func__,__LINE__,##arg)

typedef enum
{  
	IOCTL_SET_ATOP_VERSION = 1,
	IOCTL_GET_SCALER_VERSION,//2
	IOCTL_GET_ACTIONS_INFO,//3
	IOCTL_GET_LANGUAGE,//4
	IOCTL_GET_VOLUME,//5
	IOCTL_GET_NOW_IN_MODE,//6
	IOCTL_GET_WIFI_STATUS,//7
	IOCTL_GET_POWER_ON_MESSAGE,//8
	IOCTL_GEL_MODEL_NAME,//9
	IOCTL_GET_CLIENT_IP,//10
	IOCTL_SET_LAN_WIFI_OSD,//11
	IOCTL_SET_FREEZE,//12
	IOCTL_SET_HIDE,//13
	IOCTL_AM_VERSION,//14
	IOCTL_SETUP_OSD,//15
	IOCTL_GET_SOURCE,//16
	IOCTL_OPEN_SPECTRUM,//17
	IOCTL_OTA_BLOCK,//18
	SEND_RS232_CMD,//19
	CMD_GET_RESULT,//20
	EZCASTPRO_USB1_OFF,//21,richardyu 061714
	IOCTL_SET_ATOP_VOLUME, //22
}UARTCOM_IOCTL_ID;

typedef enum{
	CMD_GET_WIFI_MODE=1, //check mode first, if 0, show plug-out
	CMD_GET_WIFI_CONFIG,//2
	CMD_SET_WIFI_MODE,//3
	CMD_SET_WIFI_CONFIG,//4
	CMD_GET_PROJECTOR_STATUS,//5
	CMD_GET_CONNECT_USERS,//6
	CMD_GET_PROJECTOR_ID,//7
	CMD_SET_PROJECTOR_ID,//8
	CMD_SET_CONNECT_USERS,//9
	CMD_SET_CHANNEL_AVAILABLE,//10
	CMD_GET_CHANNEL_AVAILABLE,//11
	CMD_SET_PROJECTOR_STATUS,//12
	CMD_SET_LAN_PORT_FLAG,//13
	CMD_GET_LAN_PORT_FLAG,//14
	CMD_SET_LAN_IN_FLAG,//15
	CMD_GET_LAN_IN_FLAG,//16
	CMD_OTA_CHECK_FLAG,//17
	CMD_SET_OTA_PERCENTAGE,//18
	CMD_GET_OTA_PERCENTAGE,//19
	CMD_SET_OTA_STATUS,//20
	CMD_GET_OTA_STATUS,//21
	CMD_SET_OTA_UPDATE_NEED,//22
	CMD_GET_OTA_UPDATE_NEED,//23
	CMD_OTA_FLAG,//24
	CMD_SET_OTA_VERSION,//25
	CMD_GET_OTA_VERSION,//26
	CMD_OTA_CANCEL,//27
	CMD_OTA_SET_CHECKSUM,//28
	CMD_OTA_GET_CHECKSUM,//29
	CMD_OTA_START_UPGRADE,//30
	CMD_SET_AM_VERSION,//31
	CMD_GET_AM_VERSION,//32
	CMD_SET_DHCP_ON_OFF,//33
	CMD_GET_DHCP_ON_OFF,//34
}AM_PIPE_CMD_ID;

void custom_pipe_set_lan_in_flag(int);

#endif
