/* Automatically generated by kernel/timeconst.pl */
/* Conversion constants for HZ == 250 */

#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 250
#error "kernel/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32        U64_C(0x80000000)
#define HZ_TO_MSEC_ADJ32        U64_C(0x0)
#define HZ_TO_MSEC_SHR32        29
#define HZ_TO_MSEC_NUM          U64_C(4)
#define HZ_TO_MSEC_DEN          U64_C(1)
#define MSEC_TO_HZ_MUL32        U64_C(0x80000000)
#define MSEC_TO_HZ_ADJ32        U64_C(0x180000000)
#define MSEC_TO_HZ_SHR32        33
#define MSEC_TO_HZ_NUM          U64_C(1)
#define MSEC_TO_HZ_DEN          U64_C(4)
#define HZ_TO_USEC_MUL32        U64_C(0xfa000000)
#define HZ_TO_USEC_ADJ32        U64_C(0x0)
#define HZ_TO_USEC_SHR32        20
#define HZ_TO_USEC_NUM          U64_C(4000)
#define HZ_TO_USEC_DEN          U64_C(1)
#define USEC_TO_HZ_MUL32        U64_C(0x83126e98)
#define USEC_TO_HZ_ADJ32        U64_C(0x7ff7ced9168)
#define USEC_TO_HZ_SHR32        43
#define USEC_TO_HZ_NUM          U64_C(1)
#define USEC_TO_HZ_DEN          U64_C(4000)

#endif /* KERNEL_TIMECONST_H */
