/**
* @author Jimmy Liao
* @date: 2012.04.06
* @version: 
*	2012/04/02: draft version
* 2012/04/06: cleanup code
*/
#ifndef _WIFI_REMOTE_CONTROL_H_
#define _WIFI_REMOTE_CONTROL_H_

#include <time.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <semaphore.h>

#define NUM_BUFFERS 			4
#define BUFFER_STREAM_SIZE		(300*1024)
#define BUFFER_OUTPUT_SIZE		(3*1024*1024)
#define BUFFER_TMP_SIZE			(64*1024)

#define LOCAL_SERVER_PORT 63630
#define MAX_MSG 100

#define REMOTE_CONTROL_TIMEOUT 5*60*1000

enum REMOTE_CONTROL_COMMAND{
  COMMAND_CONNECT=0,
	COMMAND_KEY,
	COMMAND_KEYBOARD,
	COMMAND_KEYBOARD_NUMPAD,
	COMMAND_MOUSE
};

enum REMOTE_CONTROL_TYPE{
  CONN_LOOKUP=0,
  CONN_FOUND,
  CONN_CONNECT,
  CONN_DISCONNECT,
  KEY_UP=10,
  KEY_DOWN,
  KEY_LEFT,
  KEY_RIGHT,
  KEY_ENTER,
  KEY_ESC,
  MOUSE_UP=20,
  MOUSE_DOWN,
  MOUSE_LEFT,
  MOUSE_RIGHT,
  MOUSE_TAP_ONCE,
  MOUSE_TAP_DOUBLE,
  MOUSE_TAP_SCROLL                
};

typedef struct wifi_control_msg
{
	int msg_command; /* TYPE_CONNECT, TYPE_KEY, TYPE_MOUSE */
	int msg_type;
}wifi_control_msg;

//void *remote_control_main(void *arg);

int wifi_remote_control_init(void);
int wifi_remote_control_exit(void);
//void wifi_remote_control_recv_msg(void* arg);
//void wifi_remote_control_parse_image(void* arg);

//static int _inform_remote_control_change();
//int _inform_remote_control_connected();
//int _inform_remote_control_disconnected();

/**
* REMOTE_MSG_KEY key mapping space
* @note key range is 41-?
*/
/// system key message
#define SWF_REMOTE_MSG_CHANGE             (SWF_MSG_KEY | 0xC0)       ///> e.g. remote control started/not started/connected/disconnected
#define SWF_REMOTE_MSG_CONNECTED          (SWF_MSG_KEY | 0xC1)       
#define SWF_REMOTE_MSG_DISCONNECTED       (SWF_MSG_KEY | 0xC2)       

#define    REMOTE_MSG_KEY_MAPPING_BASE       0x100
#define    REMOTE_MSG_KEY_NUMBER             100
#define    REMOTE_MSG_KEY_MAPPING_MAX        (REMOTE_MSG_KEY_MAPPING_BASE+REMOTE_MSG_KEY_NUMBER)

#define    REMOTE_MSG_CTRLKEY_BASE			0x0100
#define    REMOTE_MSG_CTRLKEY_NUMBER		100
#define    REMOTE_MSG_CTRLKEY_MAPPING_MAX	(REMOTE_MSG_CTRLKEY_BASE+REMOTE_MSG_CTRLKEY_NUMBER)

#define SWF_MSG_CTRLKEY		0x1000

#define    REMOTE_MSG_KEY_LEFT		(REMOTE_MSG_KEY_MAPPING_BASE+0x25)  // 0x125
#define    REMOTE_MSG_KEY_UP		(REMOTE_MSG_KEY_MAPPING_BASE+0x26)  // 0x126
#define    REMOTE_MSG_KEY_RIGHT		(REMOTE_MSG_KEY_MAPPING_BASE+0x27)  // 0x127
#define    REMOTE_MSG_KEY_DOWN		(REMOTE_MSG_KEY_MAPPING_BASE+0x28)  // 0x128
#define    REMOTE_MSG_KEY_ENTER		(REMOTE_MSG_KEY_MAPPING_BASE+0x0d)  // 0x10d
#define    REMOTE_MSG_KEY_ESC		(REMOTE_MSG_KEY_MAPPING_BASE+0x1b)  // 0x11b

#define    REMOTE_MSG_KEY_A			(REMOTE_MSG_KEY_MAPPING_BASE+0x41)  // 0x141
#define    REMOTE_MSG_KEY_B			(REMOTE_MSG_KEY_MAPPING_BASE+0x42)  // 0x142
#define    REMOTE_MSG_KEY_C			(REMOTE_MSG_KEY_MAPPING_BASE+0x43)  // 0x143
#define    REMOTE_MSG_KEY_D			(REMOTE_MSG_KEY_MAPPING_BASE+0x44)  // 0x144
#define    REMOTE_MSG_KEY_E			(REMOTE_MSG_KEY_MAPPING_BASE+0x45)  // 0x145
#define    REMOTE_MSG_KEY_F			(REMOTE_MSG_KEY_MAPPING_BASE+0x46)  // 0x146
#define    REMOTE_MSG_KEY_G			(REMOTE_MSG_KEY_MAPPING_BASE+0x47)  // 0x147
#define    REMOTE_MSG_KEY_H			(REMOTE_MSG_KEY_MAPPING_BASE+0x48)  // 0x148
#define    REMOTE_MSG_KEY_I			(REMOTE_MSG_KEY_MAPPING_BASE+0x49)  // 0x149
#define    REMOTE_MSG_KEY_J			(REMOTE_MSG_KEY_MAPPING_BASE+0x4A)  // 0x14A
#define    REMOTE_MSG_KEY_K			(REMOTE_MSG_KEY_MAPPING_BASE+0x4B)  // 0x14B
#define    REMOTE_MSG_KEY_L			(REMOTE_MSG_KEY_MAPPING_BASE+0x4C)  // 0x14C
#define    REMOTE_MSG_KEY_M			(REMOTE_MSG_KEY_MAPPING_BASE+0x4D)  // 0x14D
#define    REMOTE_MSG_KEY_N			(REMOTE_MSG_KEY_MAPPING_BASE+0x4E)  // 0x14E
#define    REMOTE_MSG_KEY_O			(REMOTE_MSG_KEY_MAPPING_BASE+0x4F)  // 0x14F
#define    REMOTE_MSG_KEY_P			(REMOTE_MSG_KEY_MAPPING_BASE+0x50)  // 0x150
#define    REMOTE_MSG_KEY_Q			(REMOTE_MSG_KEY_MAPPING_BASE+0x51)  // 0x151
#define    REMOTE_MSG_KEY_R			(REMOTE_MSG_KEY_MAPPING_BASE+0x52)  // 0x152
#define    REMOTE_MSG_KEY_S			(REMOTE_MSG_KEY_MAPPING_BASE+0x53)  // 0x153
#define    REMOTE_MSG_KEY_T			(REMOTE_MSG_KEY_MAPPING_BASE+0x54)  // 0x154
#define    REMOTE_MSG_KEY_U			(REMOTE_MSG_KEY_MAPPING_BASE+0x55)  // 0x155
#define    REMOTE_MSG_KEY_V			(REMOTE_MSG_KEY_MAPPING_BASE+0x56)  // 0x156
#define    REMOTE_MSG_KEY_W			(REMOTE_MSG_KEY_MAPPING_BASE+0x57)  // 0x157
#define    REMOTE_MSG_KEY_X			(REMOTE_MSG_KEY_MAPPING_BASE+0x58)  // 0x158
#define    REMOTE_MSG_KEY_Y			(REMOTE_MSG_KEY_MAPPING_BASE+0x59)  // 0x159
#define    REMOTE_MSG_KEY_Z			(REMOTE_MSG_KEY_MAPPING_BASE+0x5A)  // 0x15A

#define    REMOTE_MSG_KEY_a			(REMOTE_MSG_KEY_MAPPING_BASE+0x61)  // 0x161
#define    REMOTE_MSG_KEY_b			(REMOTE_MSG_KEY_MAPPING_BASE+0x62)  // 0x161
#define    REMOTE_MSG_KEY_c			(REMOTE_MSG_KEY_MAPPING_BASE+0x63)  // 0x161
#define    REMOTE_MSG_KEY_d			(REMOTE_MSG_KEY_MAPPING_BASE+0x64)  // 0x161
#define    REMOTE_MSG_KEY_e			(REMOTE_MSG_KEY_MAPPING_BASE+0x65)  // 0x161
#define    REMOTE_MSG_KEY_f			(REMOTE_MSG_KEY_MAPPING_BASE+0x66)  // 0x161
#define    REMOTE_MSG_KEY_g			(REMOTE_MSG_KEY_MAPPING_BASE+0x67)  // 0x161
#define    REMOTE_MSG_KEY_h			(REMOTE_MSG_KEY_MAPPING_BASE+0x68)  // 0x161
#define    REMOTE_MSG_KEY_i			(REMOTE_MSG_KEY_MAPPING_BASE+0x69)  // 0x161
#define    REMOTE_MSG_KEY_j			(REMOTE_MSG_KEY_MAPPING_BASE+0x6A)  // 0x161
#define    REMOTE_MSG_KEY_k			(REMOTE_MSG_KEY_MAPPING_BASE+0x6B)  // 0x161
#define    REMOTE_MSG_KEY_l			(REMOTE_MSG_KEY_MAPPING_BASE+0x6C)  // 0x161
#define    REMOTE_MSG_KEY_m			(REMOTE_MSG_KEY_MAPPING_BASE+0x6D)  // 0x161
#define    REMOTE_MSG_KEY_n			(REMOTE_MSG_KEY_MAPPING_BASE+0x6E)  // 0x161
#define    REMOTE_MSG_KEY_o			(REMOTE_MSG_KEY_MAPPING_BASE+0x6F)  // 0x161
#define    REMOTE_MSG_KEY_p			(REMOTE_MSG_KEY_MAPPING_BASE+0x70)  // 0x161
#define    REMOTE_MSG_KEY_q			(REMOTE_MSG_KEY_MAPPING_BASE+0x71)  // 0x161
#define    REMOTE_MSG_KEY_r			(REMOTE_MSG_KEY_MAPPING_BASE+0x72)  // 0x161
#define    REMOTE_MSG_KEY_s			(REMOTE_MSG_KEY_MAPPING_BASE+0x73)  // 0x161
#define    REMOTE_MSG_KEY_t			(REMOTE_MSG_KEY_MAPPING_BASE+0x74)  // 0x161
#define    REMOTE_MSG_KEY_u			(REMOTE_MSG_KEY_MAPPING_BASE+0x75)  // 0x161
#define    REMOTE_MSG_KEY_v			(REMOTE_MSG_KEY_MAPPING_BASE+0x76)  // 0x161
#define    REMOTE_MSG_KEY_w			(REMOTE_MSG_KEY_MAPPING_BASE+0x77)  // 0x161
#define    REMOTE_MSG_KEY_x			(REMOTE_MSG_KEY_MAPPING_BASE+0x78)  // 0x161
#define    REMOTE_MSG_KEY_y			(REMOTE_MSG_KEY_MAPPING_BASE+0x79)  // 0x161
#define    REMOTE_MSG_KEY_z			(REMOTE_MSG_KEY_MAPPING_BASE+0x7A)  // 0x17A

#define    REMOTE_MSG_KEY_NUMPAD0	(REMOTE_MSG_KEY_MAPPING_BASE+0x30)  // 0x130
#define    REMOTE_MSG_KEY_NUMPAD1	(REMOTE_MSG_KEY_MAPPING_BASE+0x31)
#define    REMOTE_MSG_KEY_NUMPAD2	(REMOTE_MSG_KEY_MAPPING_BASE+0x32)
#define    REMOTE_MSG_KEY_NUMPAD3	(REMOTE_MSG_KEY_MAPPING_BASE+0x33)
#define    REMOTE_MSG_KEY_NUMPAD4	(REMOTE_MSG_KEY_MAPPING_BASE+0x34)
#define    REMOTE_MSG_KEY_NUMPAD5	(REMOTE_MSG_KEY_MAPPING_BASE+0x35)
#define    REMOTE_MSG_KEY_NUMPAD6	(REMOTE_MSG_KEY_MAPPING_BASE+0x36)
#define    REMOTE_MSG_KEY_NUMPAD7	(REMOTE_MSG_KEY_MAPPING_BASE+0x37)
#define    REMOTE_MSG_KEY_NUMPAD8	(REMOTE_MSG_KEY_MAPPING_BASE+0x38)
#define    REMOTE_MSG_KEY_NUMPAD9	(REMOTE_MSG_KEY_MAPPING_BASE+0x39)


int ezFuiRemoteStart(void);
int ezFuiRemoteStop(void);

#endif
