#1601 Quantum Plaza, No.27 Zhichun Road, Haidian District, Beijing, Actions MicroElectronics Co., Ltd.
TARGET_TYPE = app

ROOT_DIR  = ./../../..
IMAGE     = rs232_main
TARGET    = $(IMG_DIR)/$(IMAGE_APP)

INCS = $(SDK_DIR)/include \
	./include	\
	
LIBS = -lrt -pthread \

include $(ROOT_DIR)/scripts/common.mak

