#if  !define    __ACT_GLOBAL_KEY_H__
#define    __ACT_GLOBAL_KEY_H__


#define		GLOBAL_KEY_MapItem_type		0	//(null)
#define		GLOBAL_KEY_PC_UP		4	//(null)
#define		GLOBAL_KEY_HwKey1		8	//(null)
#define		GLOBAL_KEY_PC_DOWN		12	//(null)
#define		GLOBAL_KEY_HwKey2		16	//(null)
#define		GLOBAL_KEY_PC_LEFT		20	//(null)
#define		GLOBAL_KEY_HwKey3		24	//(null)
#define		GLOBAL_KEY_PC_RIGHT		28	//(null)
#define		GLOBAL_KEY_HwKey4		32	//(null)
#define		GLOBAL_KEY_PC_ESC		36	//(null)
#define		GLOBAL_KEY_HwKey5		40	//(null)
#define		GLOBAL_KEY_PC_ENTER		44	//(null)
#define		GLOBAL_KEY_HwKey6		48	//(null)
#define		GLOBAL_KEY_PC_vol+		52	//(null)
#define		GLOBAL_KEY_HwKey7		56	//(null)
#define		GLOBAL_KEY_PC_vol-		60	//(null)
#define		GLOBAL_KEY_HwKey8		64	//(null)
#define		GLOBAL_KEY_PC_LEFT		68	//(null)
#define		GLOBAL_KEY_HwKey9		72	//(null)
#define		GLOBAL_KEY_PC_RIGHT		76	//(null)
#define		GLOBAL_KEY_HwKey10		80	//(null)
#define		GLOBAL_KEY_PC_ESC		84	//(null)
#define		GLOBAL_KEY_HwKey11		88	//(null)
#define		GLOBAL_KEY_PC_ENTER		92	//(null)
#define		GLOBAL_KEY_HwKey12		96	//(null)
#define		GLOBAL_KEY_KEY_PHOTO		100	//(null)
#define		GLOBAL_KEY_HwKey13		104	//(null)
#define		GLOBAL_KEY_KEY_MUSIC		108	//(null)
#define		GLOBAL_KEY_HwKey14		112	//(null)
#define		GLOBAL_KEY_KEY_VIDEO		116	//(null)
#define		GLOBAL_KEY_HwKey15		120	//(null)
#define		GLOBAL_KEY_KEY_CALENDAR		124	//(null)
#define		GLOBAL_KEY_HwKey16		128	//(null)
#define		GLOBAL_KEY_KEY_SETUP		132	//(null)
#define		GLOBAL_KEY_HwKey17		136	//(null)
#define		GLOBAL_KEY_KEY_FILEMANAGER		140	//(null)
#define		GLOBAL_KEY_HwKey18		144	//(null)
#define		GLOBAL_KEY_KEY_EBOOK		148	//(null)
#define		GLOBAL_KEY_HwKey19		152	//(null)
#define		GLOBAL_KEY_KEY_VVD		156	//(null)
#define		GLOBAL_KEY_HwKey20		160	//(null)
#define		GLOBAL_KEY_KEY_MAINMENU		164	//(null)
#define		GLOBAL_KEY_HwKey21		168	//(null)
#define		GLOBAL_KEY_KEY_SWFPLAYER		172	//(null)
#define		GLOBAL_KEY_HwKey22		176	//(null)
#define		GLOBAL_KEY_PC_M		180	//(null)
#define		GLOBAL_KEY_HwKey23		184	//(null)
#define		GLOBAL_KEY_PC_B		188	//(null)
#define		GLOBAL_KEY_HwKey24		192	//(null)
#define		GLOBAL_KEY_KEY_VOLADD		196	//(null)
#define		GLOBAL_KEY_HwKeyVolAdd		200	//(null)
#define		GLOBAL_KEY_KEY_VOLSUB		204	//(null)
#define		GLOBAL_KEY_HwKeyVolSub		208	//(null)
#define		GLOBAL_KEY_KEY_MUTE		212	//(null)
#define		GLOBAL_KEY_HwKeyMute		216	//(null)
#define		GLOBAL_KEY_PC_F		220	//(null)
#define		GLOBAL_KEY_HwKey27		224	//(null)
#define		GLOBAL_KEY_PC_A		228	//(null)
#define		GLOBAL_KEY_HwKey28		232	//(null)
#define		GLOBAL_KEY_PC_POWER		236	//(null)
#define		GLOBAL_KEY_HwKey29		240	//(null)


#endif  //__ACT_GLOBAL_KEY_H__
