
TARGET_TYPE = app

ROOT_DIR  = ./../../..
IMAGE     = linein
TARGET    = $(IMG_DIR)/$(IMAGE_APP)


INCS = $(SDK_DIR)/include 
LIBS = $(SDK_LIB_DIR)/liblinein.so \
		   $(SDK_LIB_DIR)/libsres.so \
       $(SDK_LIB_DIR)/lib_osapi.so 

include $(ROOT_DIR)/scripts/common.mak

