TARGET_TYPE = app

ROOT_DIR  = ./../../..
IMAGE     = getDacTime
TARGET    = $(IMG_DIR)/$(IMAGE_APP)

INCS = $(SDK_DIR)/include \
	$(SDK_INCLUDE)\

 
include $(ROOT_DIR)/scripts/common.mak   

