#
# linux/drivers/devices/Makefile
#
#PREFIX := drivers/card
 
#CORE := ../Core
#INCLUDES := $(PREFIX)/Inc

obj-$(CONFIG_AM_PIPE_DEV)	+= am7x_pipe.o

am7x_pipe-objs := am_pipe.o


#EXTRA_CFLAGS := -I $(INCLUDES)		

