#ifndef __RB_SPIKEY_H__
#define __RB_SPIKEY_H__

#define SPI_MOSI_BITS      54	 // ‰≥ˆ
#define SPI_SCK_BITS	       53
#define SPI_MISO_BITS	 52    // ‰»Î
#define SPI_CSB_BITS	       51

#define SO 			am_get_gpio(SPI_MISO_BITS)
#define CSn_LOW 	am_set_gpio( SPI_CSB_BITS, 0)
#define CSn_HIGH	am_set_gpio( SPI_CSB_BITS, 1)
#define SCLK_LOW	am_set_gpio( SPI_SCK_BITS, 0)
#define SCLK_HIGH	am_set_gpio( SPI_SCK_BITS, 1)
#define SI_LOW		am_set_gpio( SPI_MOSI_BITS, 0)
#define SI_HIGH		am_set_gpio( SPI_MOSI_BITS, 1)


#define SPI_RW_ADDRESS_MASK 	0x80

#define GPBA02_BASE_BUFFER     	0x00
#define GPBA02_BASE_DIR             0x04
#define GPBA02_BASE_ATTR          	0x08
#define GPBA02_BASE_DATA          0x0c

#define GPBA02_OFFSET_PORT_A 	0x00
#define GPBA02_OFFSET_PORT_B	0x01
#define GPBA02_OFFSET_PORT_C	0x02

#define GPBA02_PORTA_BUFFER    	(GPBA02_BASE_BUFFER	+GPBA02_OFFSET_PORT_A)
#define GPBA02_PORTA_DIR           (GPBA02_BASE_DIR	+GPBA02_OFFSET_PORT_A)
#define GPBA02_PORTA_ATTR       	(GPBA02_BASE_ATTR	+GPBA02_OFFSET_PORT_A)
#define GPBA02_PORTA_DATA        	(GPBA02_BASE_DATA	+GPBA02_OFFSET_PORT_A)

#define GPBA02_PORTB_BUFFER    	(GPBA02_BASE_BUFFER+GPBA02_OFFSET_PORT_B)
#define GPBA02_PORTB_DIR           (GPBA02_BASE_DIR	+GPBA02_OFFSET_PORT_B)
#define GPBA02_PORTB_ATTR       	(GPBA02_BASE_ATTR	+GPBA02_OFFSET_PORT_B)
#define GPBA02_PORTB_DATA        	(GPBA02_BASE_DATA	+GPBA02_OFFSET_PORT_B)

#define GPBA02_PORTC_BUFFER    	(GPBA02_BASE_BUFFER	+GPBA02_OFFSET_PORT_C)
#define GPBA02_PORTC_DIR           (GPBA02_BASE_DIR	+GPBA02_OFFSET_PORT_C)
#define GPBA02_PORTC_ATTR       	(GPBA02_BASE_ATTR	+GPBA02_OFFSET_PORT_C)
#define GPBA02_PORTC_DATA        	(GPBA02_BASE_DATA	+GPBA02_OFFSET_PORT_C)

#define KEYSCAN_OUT_BUFFER      	GPBA02_PORTA_BUFFER          
#define KEYSCAN_OUT_DIR            	GPBA02_PORTA_DIR          
#define KEYSCAN_OUT_ATTR          	GPBA02_PORTA_ATTR
#define KEYSCAN_OUT_DATA          GPBA02_PORTA_DATA          

#define KEYSCAN_IN_BUFFER      	GPBA02_PORTB_BUFFER          
#define KEYSCAN_IN_DIR            	GPBA02_PORTB_DIR          
#define KEYSCAN_IN_ATTR           	GPBA02_PORTB_ATTR
#define KEYSCAN_IN_LOW_DATA    GPBA02_PORTB_DATA  

#define KEYSCAN_IN1_BUFFER      	GPBA02_PORTC_BUFFER          
#define KEYSCAN_IN1_DIR            	GPBA02_PORTC_DIR          
#define KEYSCAN_IN1_ATTR          	GPBA02_PORTC_ATTR
#define KEYSCAN_IN_HIGH_DATA   GPBA02_PORTC_DATA  

#endif    

