#1601 Quantum Plaza, No.27 Zhichun Road, Haidian District, Beijing, Actions MicroElectronics Co., Ltd.
TARGET_TYPE = app

ROOT_DIR  = ./../../../..
IMAGE     = framectrl
TARGET    = $(IMG_DIR)/$(IMAGE_APP)

LIBS = -lpthread -lrt -ldl --start-group -lm -lgcc --end-group 

include $(ROOT_DIR)/scripts/common.mak

